package club;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jwvandyke
 */
public class BreakfastClub extends javax.swing.JFrame {
    
    int numberOfBars = 0;
    
    /**
     * Creates new form BreakfastClub
     */
    private HistoMaker H;
    private Statistics s;
    private ArrayList<Double> al;
    public BreakfastClub() {
        H = new HistoMaker();
        initComponents();
        pnlDisplay.setLayout(new BorderLayout());
        pnlDisplay.add(H,BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        tabStatistics = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaNums = new javax.swing.JTextArea();
        btnDisplay = new javax.swing.JButton();
        pnlCustomize = new javax.swing.JPanel();
        btnDisplayCustomized = new javax.swing.JButton();
        lblHistogram = new javax.swing.JLabel();
        lblXTitle = new javax.swing.JLabel();
        lblYTitle = new javax.swing.JLabel();
        lblNumOfBars = new javax.swing.JLabel();
        cboNumOfBars = new javax.swing.JComboBox();
        txtYAxis = new javax.swing.JTextField();
        txtXTitle = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        jcc = new javax.swing.JColorChooser();
        pnlDisplay = new javax.swing.JPanel();
        pnlStats = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        lblMode = new javax.swing.JLabel();
        lblModeData = new javax.swing.JLabel();
        lblMedianData = new javax.swing.JLabel();
        lblMedian = new javax.swing.JLabel();
        lblMean = new javax.swing.JLabel();
        lblMeanData = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mbFile = new javax.swing.JMenu();
        mnitLoad = new javax.swing.JMenuItem();
        mnitSave = new javax.swing.JMenuItem();
        mnitSaveHisto = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 725));
        setPreferredSize(new java.awt.Dimension(600, 725));

        lblTitle.setFont(new java.awt.Font("Brush Script MT", 0, 54)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("The Breakfast Club Histogram");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tabStatistics.setPreferredSize(new java.awt.Dimension(723, 800));

        txtAreaNums.setColumns(20);
        txtAreaNums.setLineWrap(true);
        txtAreaNums.setRows(5);
        jScrollPane1.setViewportView(txtAreaNums);

        btnDisplay.setText("Display Histogram");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addComponent(btnDisplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisplay)
                .addContainerGap())
        );

        tabStatistics.addTab("Enter Data", jPanel1);

        btnDisplayCustomized.setText("Display Histogram");
        btnDisplayCustomized.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayCustomizedActionPerformed(evt);
            }
        });

        lblHistogram.setText("Histogram Title:");

        lblXTitle.setText("X-Axis Title:");

        lblYTitle.setText("Y-Axis Title:");

        lblNumOfBars.setText("Number of Bars:");

        cboNumOfBars.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Square Root of n", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        cboNumOfBars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNumOfBarsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCustomizeLayout = new javax.swing.GroupLayout(pnlCustomize);
        pnlCustomize.setLayout(pnlCustomizeLayout);
        pnlCustomizeLayout.setHorizontalGroup(
            pnlCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustomizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDisplayCustomized, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addGroup(pnlCustomizeLayout.createSequentialGroup()
                        .addGroup(pnlCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblNumOfBars, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblYTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblXTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblHistogram, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTitle)
                            .addComponent(txtXTitle)
                            .addComponent(txtYAxis)
                            .addComponent(cboNumOfBars, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCustomizeLayout.setVerticalGroup(
            pnlCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustomizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHistogram)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblXTitle)
                    .addComponent(txtXTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYTitle)
                    .addComponent(txtYAxis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCustomizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumOfBars)
                    .addComponent(cboNumOfBars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcc, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDisplayCustomized)
                .addContainerGap())
        );

        tabStatistics.addTab("Customization", pnlCustomize);

        javax.swing.GroupLayout pnlDisplayLayout = new javax.swing.GroupLayout(pnlDisplay);
        pnlDisplay.setLayout(pnlDisplayLayout);
        pnlDisplayLayout.setHorizontalGroup(
            pnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        pnlDisplayLayout.setVerticalGroup(
            pnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );

        tabStatistics.addTab("Display Histogram", pnlDisplay);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Class", "Frequency", "Relative Frequency"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblData);

        lblMode.setText("Mode:");

        lblModeData.setText("0.0");

        lblMedianData.setText("0.0");

        lblMedian.setText("Median:");

        lblMean.setText("Mean:");

        lblMeanData.setText("0.0");

        javax.swing.GroupLayout pnlStatsLayout = new javax.swing.GroupLayout(pnlStats);
        pnlStats.setLayout(pnlStatsLayout);
        pnlStatsLayout.setHorizontalGroup(
            pnlStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addGroup(pnlStatsLayout.createSequentialGroup()
                        .addGroup(pnlStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlStatsLayout.createSequentialGroup()
                                .addComponent(lblMean)
                                .addGap(18, 18, 18)
                                .addComponent(lblMeanData, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlStatsLayout.createSequentialGroup()
                                .addComponent(lblMode)
                                .addGap(18, 18, 18)
                                .addComponent(lblModeData))
                            .addGroup(pnlStatsLayout.createSequentialGroup()
                                .addComponent(lblMedian)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMedianData, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlStatsLayout.setVerticalGroup(
            pnlStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMean)
                    .addComponent(lblMeanData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedian)
                    .addComponent(lblMedianData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMode)
                    .addComponent(lblModeData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        tabStatistics.addTab("Statistics", pnlStats);

        mbFile.setText("File");

        mnitLoad.setText("Load Data File");
        mnitLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitLoadActionPerformed(evt);
            }
        });
        mbFile.add(mnitLoad);

        mnitSave.setText("Save Data to File");
        mnitSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitSaveActionPerformed(evt);
            }
        });
        mbFile.add(mnitSave);

        mnitSaveHisto.setText("Save Histogram");
        mnitSaveHisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitSaveHistoActionPerformed(evt);
            }
        });
        mbFile.add(mnitSaveHisto);

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mbFile.add(jMenuItem1);

        menuBar.add(mbFile);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabStatistics, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabStatistics, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnitLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitLoadActionPerformed

        JFileChooser fc = new JFileChooser();
        int x = fc.showOpenDialog(fc);

        txtAreaNums.setText("");
        
        ArrayList<Double> al = new ArrayList();

        try {

            FileReader fr = new FileReader(fc.getSelectedFile());
            BufferedReader br = new BufferedReader(fr);
            Scanner in = new Scanner(br);

            while (in.hasNextDouble()) {

                Double num = in.nextDouble();

                txtAreaNums.append(num.toString() + " ");

            }

        }

        catch (FileNotFoundException fnf) {

        }
        
    }//GEN-LAST:event_mnitLoadActionPerformed

    private void mnitSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitSaveActionPerformed
        
        JFileChooser jfc = new JFileChooser();
        
        int x = jfc.showSaveDialog(null);
        
        if (x == JFileChooser.APPROVE_OPTION) {
            
            try {
                
                FileWriter fw = new FileWriter(jfc.getSelectedFile() + ".txt");
                
                String data = txtAreaNums.getText();

                ArrayList<Double> nums = new ArrayList<Double>();

                Matcher m = Pattern.compile(("\\d+(\\.\\d+)?")).matcher(data);

                if (m.find()) {

                    nums.add(Double.parseDouble(m.group(0)));

                }

                m = Pattern.compile(("\\s\\d+(\\.\\d+)?")).matcher(data);

                while (m.find()) {

                    nums.add(Double.parseDouble(m.group(0)));

                }
                
                for (int i = 0; i < nums.size(); i++) {
                    
                    fw.write(nums.get(i).toString() + "\n");
                    
                }//end for
                
                fw.flush();
                
                fw.close();
                
            }//end try
            
            catch (Exception ex) {
                
                
                
            }//end catch
            
        }//end if
        
    }//GEN-LAST:event_mnitSaveActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        
        String x = txtAreaNums.getText();
        
        ArrayList<Double> nums = new ArrayList<Double>();

        Matcher m = Pattern.compile((("\\d+(\\.\\d+)?"))).matcher(x);

        if (m.find()) {

            nums.add(Double.parseDouble(m.group(0)));

        }
        
        m = Pattern.compile(("\\s\\d+(\\.\\d+)?")).matcher(x);

        while (m.find()) {

            nums.add(Double.parseDouble(m.group(0)));

        }
        H.setData(nums);
        
        s = new Statistics(nums,this);
        
        if (numberOfBars == 0) {
            
            s.setTable();
            
        }
        
        else {
            
            s.n = numberOfBars;
            s.setTable();
            
        }
        
        if(!H.getState())// start the histogram diplay if not already started
            H.start();
        
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void mnitSaveHistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitSaveHistoActionPerformed
        
        JFileChooser jfc = new JFileChooser();
        
        int x = jfc.showSaveDialog(null);
        
        if (x == JFileChooser.APPROVE_OPTION) {
            
        Container C = H;
        
        //BufferedImage im = H.crea.createBufferedImage(H.getWidth(), H.getHeight());
        
        try{
            BufferedImage image = new Robot().createScreenCapture(new Rectangle(H.getLocationOnScreen().x, H.getLocationOnScreen().y, H.getWidth(), H.getHeight()));
            ImageIO.write(image, "png", new File(jfc.getSelectedFile()+".png"));
                
            }//end try
            
            catch (Exception ex) {
                
                
                
            }//end catch
            
        }//end if
    }//GEN-LAST:event_mnitSaveHistoActionPerformed

    private void btnDisplayCustomizedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayCustomizedActionPerformed
        
        String title = txtTitle.getText();
        String xTitle = txtXTitle.getText();
        String yTitle = txtYAxis.getText();
        String numOfBars = (String)cboNumOfBars.getSelectedItem();
        
        if (numOfBars.equals("Square Root of n")) {
            
            numberOfBars = 0;
            //Need to pass this to MathClass someway
            
            
        }
        
        else {
            
            numberOfBars = Integer.parseInt(numOfBars);
            H.setN(numberOfBars);
            
        }
        
        H.title = title;
        H.xAxis = xTitle;
        H.yAxis = yTitle;
        
        Color color = jcc.getColor();
        H.setC(color);
        
        btnDisplayActionPerformed(evt);
    }//GEN-LAST:event_btnDisplayCustomizedActionPerformed

    private void cboNumOfBarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNumOfBarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNumOfBarsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BreakfastClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BreakfastClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BreakfastClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BreakfastClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BreakfastClub().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnDisplayCustomized;
    private javax.swing.JComboBox cboNumOfBars;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JColorChooser jcc;
    private javax.swing.JLabel lblHistogram;
    public javax.swing.JLabel lblMean;
    public javax.swing.JLabel lblMeanData;
    public javax.swing.JLabel lblMedian;
    public javax.swing.JLabel lblMedianData;
    public javax.swing.JLabel lblMode;
    public javax.swing.JLabel lblModeData;
    private javax.swing.JLabel lblNumOfBars;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblXTitle;
    private javax.swing.JLabel lblYTitle;
    private javax.swing.JMenu mbFile;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnitLoad;
    private javax.swing.JMenuItem mnitSave;
    private javax.swing.JMenuItem mnitSaveHisto;
    private javax.swing.JPanel pnlCustomize;
    private javax.swing.JPanel pnlDisplay;
    private javax.swing.JPanel pnlStats;
    private javax.swing.JTabbedPane tabStatistics;
    public javax.swing.JTable tblData;
    private javax.swing.JTextArea txtAreaNums;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtXTitle;
    private javax.swing.JTextField txtYAxis;
    // End of variables declaration//GEN-END:variables
}
